{
    "th19_net_connected": "Successfully connected to server",
    "th19_net_playername_1": "Change the player's name.",
    "th19_net_alphanumeric": "You can use only alphanumeric characters and some symbols.",
    "th19_net_roomrename_1": "Change the room's name.",
    "th19_net_roomrename_2": "Please provide this room's name with the player you want to play with.",
    "th19_net_room_joining": "Trying to join the room.",
    "th19_net_room_joined": "Joined the room.",
    "th19_net_waiting_for_opponent": "Waiting for opponents.",
    "th19_net_try_again": "Please try again later.",
    "th19_net_joined_p1": "An opponent has been found. You are Player 1 (on the left side).",
    "th19_net_joined_p2": "An opponent has been found. You are Player 2 (on the right side).",
    "th19_net_wait_for_p1": "Waiting for the action on Player 1's side.",
    "th19_net_wait_for_p2": "Waiting for the action on Player 2's side.",
    "th19_net_start": "Please press the action button to start playing.",
    "th19_net_change_delay": "You can change the delay settings for the left and right sides.",
    "th19_net_latency_low": "Delay setting: «low latency»",
    "th19_net_latency_low_notice": "Low latency: suitable for high-speed connection",
    "th19_net_latency_mid": "Delay setting: «middle latency»",
    "th19_net_latency_mid_notice": "Less operable: suitable for choppy connection",
    "th19_net_latency_high": "Delay setting: «high latency»",
    "th19_net_latency_high_notice": "Can barely play: suitable for quite bad connection",
    "th19_net_latency_none": "Delay setting: «no delay»",
    "th19_net_latency_none_notice": "Can play as easily as in the local play: suitable for super-high connection",
    "th19_net_connection_failed": "Connection failed.",
    "th19_net_failed": "Failed"
}