{
    "0+Boss00BossCard1+0": "Signo de Metal y Agua \"Lluvia de Cuchillos de Zafiro\"",
    "0+Boss00BossCard1H+0": "Signo de Metal y Agua \"Lluvia de Cuchillos de Zafiro\"",
    "1+Boss00BossCard1+0": "Protectora de Hallownest \"Danmaku de Seda\"",
    "1+Boss00BossCard1H+0": "Legado de Hallownest \"Explosión sellada\"",
    "4+Boss00BossCard1+0": "Gordito de Hollownest \"Retorno\"",
    "4+Boss00BossCard1+4": "\"Teorías Fumadas 4\"",
    "5+Boss00BossCard1+0": "Makai \"Sueño del Mundo Demonio\"",
    "5+Boss00BossCard1+4": "\"Génesis de Makai\"",
    "6+Boss00BossCard1+0": "Dios del Clima \"Chispa del Caos Torrencial\"",
    "0+BossCard2+0": "Signo de Fuego y Agua \"Bipolaridad Elemental\"",
    "0+BossCard3+0": "\"Luna del Ocaso Universal\"",
    "2+Boss00BossCard1+0": "\"Pureza del Vacío\"",
    "2+Boss00BossCard1+6": "\"Memoria del Legado Pálido\"",
    "3+Boss00BossCard1+0": "Sello del Sol \"Luz Inmortal\"",
    "3+Boss00BossCard1+6": "Destello \"Radiante Furia Absoluta\"",
    "7+Boss00BossCard1+0": "Vacío \"Llamado del Abismo\"",
    "8+BossCard1+0": "Reflejo del Pasado y Presente \"Ascenso del Vacío\"",
    "9+BossCard1+0": "\"Barrera de la llama de Azufre\"",
    "10+BossCard1+0": "Símbolo Complejo \"Espirografo Asimétrico\"",
    "10+BossCard2+0": "\"Flor de Loto Azúl en el Lago Cocito\"",
    "10+BossCard3+0": "\"Juicio Divino\"",
    "11+BossCard1+0": "Elemento Primordial \"Luz\"",
    "11+BossCard2+0": "Lighderiu \"Iluminación Arcana\"",
    "11+BossCard3+0": "\"Mundo de Luz y Dioses\"",
    "12+BossCard1+0": "Bendición\"Eterna Luz Sagrada\"",
    "12+BossCard2+0": "Luz Concentrada \"Iluminación Etérea\"",
    "12+BossCard3+0": "\"Sol Radiante en el Imperio Sagrado\"",
    "13+BossCard1+0": "Sello Danmaku \"Barrera del Caos y la Paz\"",
    "13+BossCard2+0": "Sello Legendario \"Purificación del Mundo Irreparable\"",
    "13+BossCard3+0": "\"CaosUniversalEnReinoPecador-ViajeProfanoYRealPorPureza\"",
    "13+BossCard4+0": "ANTIGUARESURRECCIÓN \"PerseveranciaDeLaTiranaDeLosTiranos\"",
    "14+BossCard1+0": "\"Magia Artificial\"",
    "15+BossCard1+0": "\"Gran Aluvión Galáctico\"",
    "16+BossCard1+0": "\"Reencarnación del Espíritu Demoniaco\"",
    "17+BossCard1+0": "\"Jardín de Mugekkan\"",
    "18+BossCard1+0": "\"Descendiente del Dios de la Muerte\"",
    "18+BossCard2+0": "Enésimo Armageddon \"Lado Oscuro\"",
    "18+BossCard3+0": "\"Sangre de la Guerra Milenaria\""
}