{
    "0+Boss00BossCard1+0": "Signo de Metal y Agua \"Lluvia de Cuchillos de Zafiro\"",
    "0+Boss00BossCard1H+0": "Signo de Metal y Agua \"Lluvia de Cuchillos de Zafiro\"",
    "0+BossCard2+0": "Signo de Fuego y Agua \"Bipolaridad Elemental\"",
    "0+BossCard3+0": "\"Luna del Ocaso Universal\"",
    "1+Boss00BossCard1+0": "Protectora de Hallownest \"Danmaku de Seda\"",
    "1+Boss00BossCard1H+0": "Legado de Hallownest \"Explosión sellada\"",
    "2+Boss00BossCard1+0": "\"Pureza del Vacío\"",
    "2+Boss00BossCard1+6": "\"Memoria del Legado Pálido\"",
    "3+Boss00BossCard1+0": "Sello del Sol \"Luz Inmortal\"",
    "3+Boss00BossCard1+6": "Destello \"Radiante Furia Absoluta\"",
    "3+BossCardPV+0": "Destello \"Radiante Furia Absoluta\"",
    "3+BossCardE1+0": "\"Soles Gemelos en el Universo\" -Radiante",
    "4+Boss00BossCard1+0": "Gordito de Hollownest \"Retorno\"",
    "4+Boss00BossCard1+4": "\"Teorías Fumadas 4\"",
    "5+Boss00BossCard1+0": "Makai \"Sueño del Mundo Demonio\"",
    "5+Boss00BossCard1+4": "\"Génesis de Makai\"",
    "5+BossCard1E+0": "\"Regreso de la Madre Creadora\"",
    "6+Boss00BossCard1+0": "Dios del Clima \"Chispa del Caos Torrencial\"",
    "7+Boss00BossCard1+0": "Vacío \"Llamado del Abismo\"",
    "8+BossCard1+0": "Reflejo del Pasado y Presente \"Ascenso del Vacío\"",
    "9+BossCard1+0": "\"Barrera de la llama de Azufre\"",
    "10+BossCard1+0": "Símbolo Complejo \"Espirografo Asimétrico\"",
    "10+BossCard2+0": "\"Flor de Loto Azúl en el Lago Cocito\"",
    "10+BossCard3+0": "\"Juicio Divino\"",
    "11+BossCard1+0": "Elemento Primordial \"Luz\"",
    "11+BossCard1E+0": "Elemento Primordial \"Luz\"",
    "11+BossCard2+0": "Lighderiu \"Iluminación Arcana\"",
    "11+BossCard3+0": "\"Mundo de Luz y Dioses\"",
    "12+BossCard1+0": "Bendición\"Eterna Luz Sagrada\"",
    "12+BossCard1E+0": "\"Soles Gemelos en el Universo\" -Sagrado",
    "12+BossCard2+0": "Luz Concentrada \"Iluminación Etérea\"",
    "12+BossCard3+0": "\"Sol Radiante en el Imperio Sagrado\"",
    "13+BossCard1+0": "Sello Danmaku \"Barrera del Caos y la Paz\"",
    "13+BossCard2+0": "Sello Legendario \"Purificación del Mundo Irreparable\"",
    "13+BossCard3+0": "\"CaosUniversalEnReinoPecador-ViajeProfanoYRealPorPureza\"",
    "13+YouGotTrolled+0": "\"CaosUniversalEnReinoPecador-ViajeProfanoYRealPorPureza\"",
    "13+FINALJUDGMENT+0": "ANTIGUARESURRECCIÓN \"PerseveranciaDeLaTiranaDeLosTiranos\"",
    "14+BossCard1+0": "\"Magia Artificial\"",
    "15+BossCard1+0": "\"Gran Aluvión Galáctico\"",
    "16+BossCard1+0": "\"Reencarnación del Espíritu Demoniaco\"",
    "17+BossCard1+0": "\"Jardín de Mugekkan\"",
    "18+BossCard1+0": "\"Descendiente del Dios de la Muerte\"",
    "18+BossCard1E+0": "\"Descendiente del Dios de la Muerte\"",
    "18+BossCard2+0": "Enésimo Armageddon \"Lado Oscuro\"",
    "18+BossCard2E+0": "Enésimo Armageddon \"Lado Oscuro\"",
    "18+BossCard3+0": "\"Sangre de la Guerra Milenaria\"",
    "18+BossCard3E+0": "\"Sangre de la Guerra Milenaria\"",
    "0+LASTWORD+0": "\"FUEGO PURIFICADOR DE LA LUNA\"",
    "1+LASTWORD+0": "\"LEYENDAS DEL PASADO DE HALLOWNEST\"",
    "2+LASTWORD+0": "\"IMPUREZA EN LA VASIJA EMOCIONAL\"",
    "3+LASTWORD+0": "\"RESPLANDOR FINAL DE LA LUZ DESVANECIENTE\"",
    "5+LASTWORD+0": "\"ÚLTIMO RECITAL DE CREACIÓN\"",
    "6+LASTWORD+0": "\"NUBE DE LA CATÁSTROFE DIVINA\"",
    "7+LASTWORD+0": "\"FANTASMA DEL ÍDOLO DEL VACÍO\"",
    "8+LASTWORD+0": "\"REQUIEM DEL VACÍO\"",
    "9+LASTWORD+0": "\"CALAMIDAD ARDIENTE DEL UNIVERSO\"",
    "10+LASTWORD+0": "\"LA PARUSÍA DEL FINAL DE LOS TIEMPOS\"",
    "11+LASTWORD+0": "\"MUNDO CORONADO POR DIOSES\"",
    "12+LASTWORD+0": "\"IMPERIAL Y SAGRADO SOL\"",
    "13+LASTWORD+0": "\"VIAJE ENTRE DIMENSIONES CAÓTICAS -UNIVERSO CRUEL\"",
    "14+LASTWORD+0": "\"ARCHIVOS DEL ESTUDIO INCOMPLETO\"",
    "15+LASTWORD+0": "\"PODER VERDADERO DEL DIOS CREADOR\"",
    "16+LASTWORD+0": "\"FANTASÍA DEL DESEO DEMONIACO\"",
    "17+LASTWORD+0": "\"FLOR ANTÍGUA EN LA OSCURIDAD\"",
    "18+LASTWORD+0": "\"TRASCENDENCIA: PUERTA DEL DIGNO FINAL DE LA VIDA\""
}