{
    "0": "Caballero más fuerte <Gran Golpe>",
    "2": "Sello de fuerza <Golpe de mazo>",
    "5": "Sello de fuerza <Golpe de mazo>",
    "6": "LAST BREATH: Mazo <Disparo de furia>",
    "9": "LAST BREATH: Mazo <Disparo de furia>",
    "10": "Sello de polilla <Polvo de ensueño>",
    "12": "Sello de polilla <Polvo de ensueño>",
    "14": "Signo viviente <Filo Fantasma>",
    "18": "LAST BREATH: Sueño <Memoria del guerrero>",
    "21": "LAST BREATH: Sueño <Memoria del guerrero>",
    "22": "Sello del Abismo <Cuerpo Vacío>",
    "24": "Sello del Abismo <Cuerpo Vacío>",
    "26": "Infección <Escapa de la Luz>",
    "28": "Infección <Escapa de la Luz>",
    "29": "Infección <Escapa de la Luz>",
    "30": "Sello Radiante <Sueño Cegador>",
    "32": "Sello Radiante <Sueño Cegador>",
    "34": "Signo de Sueño <Sin vacío en el interior>",
    "36": "Signo de Sueño <Sin vacío en el interior>",
    "37": "Signo de Sueño <Sin vacío en el interior>",
    "38": "LAST BREATH: Sello de infección <Familiar Corrupto>",
    "42": "Sello de Araña <Descendiente de Nido Profundo>",
    "44": "Sello de Araña <Descendiente de Nido Profundo>",
    "46": "Tejedora <Anillo de Seda>",
    "48": "Tejedora <Anillo de Seda>",
    "50": "Protectora de Hallownest <Aguja y Seda>",
    "52": "Protectora de Hallownest <Aguja y Seda>",
    "54": "LAST BREATH: Hija de Hallownest <Pálida Canción de Seda>",
    "58": "Sello de Pesadilla <Alimenta al Niño>",
    "60": "Sello de Pesadilla <Alimenta al Niño>",
    "62": "Corazón Pesadilla <Esencia del Caos>",
    "64": "Corazón Pesadilla <Esencia de la Calamidad>",
    "66": "Compañía Grimm <Inferno King Grimm>",
    "69": "Compañia Grimm <Absolute Inferno King Grimm>",
    "70": "<Locura de Pesadilla>",
    "74": "LAST BREATH: <Completa el Ritual>",
    "76": "LAST BREATH: <Ritual de pesadilla completado>",
    "78": "<Ilumina el Abismo>",
    "82": "<Resplandor Absoluto>",
    "86": "<Purifica el Reino>",
    "88": "<Imperios Vacíos Purificados>",
    "90": "<La Sombra No Existirá>",
    "94": "<Diosa Absoluta>",
    "98": "<Bajo mi control>",
    "101": "<Mente Impura Bajo Mi Poder>",
    "102": "LAST BREATH: Sello del Sol <Luz Eterna de Radiance>",
    "104": "LAST BREATH: Sello Radiante <Ultimátum de Any Radiance>",
    "106": "<Propagación De La Infección>",
    "107": "Signo de Luz <Llama Brillante>",
    "108": "Sueño Maldito <Memoria Infectada>",
    "109": "Vasija <Cadenas Del Sello>",
    "110": "Sombra <Libera El Vacío>",
    "111": "Sello <Entierra La Infección>",
    "112": "<Libertad Al Sol>",
    "113": "Vasija <Último Lamento Impuro>",
    "114": "Sombra <Una Vasija Puede Llorar>",
    "115": "Sello <El Sacrifício en Vano>",
    "116": "<La Maldición De Los Sueños>",
    "117": "<El Sufrimiento Silenciado>",
    "118": "LAST BREATH: <Mente Poseída y Destrozada>",
    "45": "Protectora de Hallownest <Aguja y Seda>"
}