{
    "0": "Strongest Knight <Great Strike>",
    "2": "Streight Sign <Mace Hit>",
    "5": "Streight Sign <Mace Hit>",
    "6": "LAST BREATH: Mace <Fury Shot>",
    "9": "LAST BREATH: Mace <Fury Shot>",
    "10": "Moth Sign <Dream Dust>",
    "12": "Moth Sign <Dream Dust>",
    "14": "Living Sign <Ghost Blade>",
    "18": "LAST BREATH: Dream <Warrior Memory>",
    "21": "LAST BREATH: Dream <Warrior Memory>",
    "22": "Abyss Sign <Empty Body>",
    "24": "Abyss Sign <Empty Body>",
    "26": "Infection <Escape The Light>",
    "28": "Infection <Escape The Light>",
    "29": "Infection <Escape The Light>",
    "30": "Radiant Sign <Blinding Dream>",
    "32": "Radiant Sign <Blinding Dream>",
    "34": "Dream Sign <No Void Inside>",
    "36": "Dream Sign <No Void Inside>",
    "37": "Dream Sign <No Void Inside>",
    "38": "LAST BREATH: Infection Sign <Corrupted Kin>",
    "42": "Spider Sign <Deepness Descendant>",
    "44": "Spider Sign <Deepness Descendant>",
    "46": "Weaver <Ring Of Silk>",
    "48": "Weaver <Ring Of Silk>",
    "50": "Hallownest Protector <Needle & Silk>",
    "52": "Hallownest Protector <Needle & Silk>",
    "54": "LAST BREATH: Daughter Of Hallownest <Pale Silksong>",
    "58": "Nightmare Sign <Cursed Flame in Rebirth>",
    "60": "Nightmare Sign <Eternal Flame in Rebirth>",
    "62": "Nightmare Heart <Essence Of Chaos>",
    "64": "Nightmare Heart <Essence Of Calamity>",
    "66": "Grimm Troupe <Inferno King Grimm>",
    "69": "Grimm Troupe <Absolute Inferno King Grimm>",
    "70": "<Nightmare Madness>",
    "74": "LAST BREATH: <Finish The Ritual>",
    "76": "LAST BREATH: <Finished Ritual Of Nightmares>",
    "78": "<Enlight The Abyss>",
    "82": "<Absolute Shine>",
    "86": "<Purify The Kingdom>",
    "88": "<Purified Empty Empires>",
    "90": "<Shade will not Exist>",
    "94": "<Absolute Goddess>",
    "98": "<Beneath my Control>",
    "101": "<Impure Mind Under my Power>",
    "102": "LAST BREATH: Sun Sign <Eternal Light of the Radiance>",
    "104": "LAST BREATH: Radiant Sign <Ultimatum of Any Radiance>",
    "106": "<The Spread of the Infection>",
    "107": "Light Sign <Shining Blaze>",
    "108": "Cursed Dream <Infected Memory>",
    "109": "Vessel <Chains Of The Seal>",
    "110": "Shade <Unleash The Void>",
    "111": "Seal <Bury the Infection>",
    "112": "<Freedom to the Sun>",
    "113": "Vessel <A last impure lament>",
    "114": "Shade <Vessel can Cry>",
    "115": "Seal <The Sacrifice In Vain>",
    "116": "<The Dreams Curse>",
    "117": "<Silenced Suffering>",
    "118": "LAST BREATH: <Possesed and Shattered Mind>",
    "119": "THE FALL OF HALLOWNEST: <Hope Fallen In Divine Dawn>",
    "45": "Spider Sign <Deepness Descendant>"
}