{
    "th07 Menu Start": "¡Empieza la historia!",
    "th07 Menu Extra Start": "Comienza la Extra...",
    "th07 Menu Quit": "¿Te vaz a ir?",
    "th06 Bomb Marisa B": "Prisma de Newton Dividiendo Luz en Elementos",
    "th08 Bomb Reimu": "Signo Lunar <Fases de la Luna>",
    "th08 Bomb Reimu Last": "Signo Lunar <Luna Llena de Fantasía en el Zodiaco>",
    "th08 Bomb Yukari": "Calamidad <Arco de Profanación>",
    "th08 Bomb Yukari Last": "Antigua Resurreción <Invocación de la Última Desilusión>",
    "th08 Bomb Marisa Last": "Signo Solar <Sol Brillante Alineado con el Zodiaco>",
    "th08 Bomb Alice": "Signo Floral -Amapola de un Sacrificio",
    "th08 Bomb Alice Last": "Signo Floral -Pesadilla de Flores Multicolor",
    "th08 Spell Dissolve": "\"ANTIGUA RESURRECIÓN\"",
    "th06_ascii_fullpower": "Poder Máximo!",
    "th06_ascii_centered_spell_bonus": "Bonus de Spell Card!",
    "th08 config": "Touhou Gosshokumugen - Environment Custom Program",
    "th08 Stats Reimu & Yukari": "Sumiyoshi & Caty",
    "th08 Stats Marisa & Alice": "Sakura & Eiva",
    "th08 Stats Reimu": "Sumiyoshi Tsukuyomi",
    "th08 Stats Yukari": "Caty Yafumo",
    "th08 Stats Marisa": "Sakura Amaterasu",
    "th08 Stats Alice": "Eiva Uke Mochi",
    "th08 JP": "Eclipse Infinito",
    "th08 Spell Condition Line 2 215": "Con Sakura.",
    "th08 Spell Condition Line 1 216": "Seleccionable cuando consigues el Modo Difícil o Lunático con Sumiyoshi.",
    "th08": "Touhou Gosshokumugen ~ Eclipse Infinito"
}