{
    "th07 Menu Start": "Iniciar juego.",
    "th07 Menu Extra Start": "Iniciar nivel extra.",
    "th07 Menu Practice Start": "Seleccionar nivel y prácticar.",
    "th07 Menu Result": "Revisar historial de Spell Cards y puntuaciones.",
    "th07 Menu Music Room": "Escuchar música del juego.",
    "th07 Menu Replay": "Observa las repeticiones",
    "th07 Menu Option": "Configura las opciones del juego.",
    "th07 Menu Quit": "Salir del juego.",
    "th07 Option Player": "Selecciona el número inicial de vidas. (Por defecto: 3)",
    "th07 Option Graphic": "Cambia la profundidad de color de pantalla. Se ve mejor en 32 bits.",
    "th07 Option BGM": "Cambia el formato para reproducir la música. (Por defecto: WAV)",
    "th07 Option Sound": "Elige si se reproducen los efectos de sonido o no.",
    "th07 Option Window Mode": "Cambia entre pantalla completa o modo ventana.",
    "th07 Option Slow Mode": "Ralentiza el juego cuando hay muchos proyectiles en pantalla. (Aunque no tendrás grabaciones ni alta puntuación)",
    "th07 Option Reset": "Restaurar configuración por defecto.",
    "th07 Option Key Config": "Configurar controles del juego.",
    "th07 Option Quit": "Sal del menú de opciones.",
    "th07 Key Shot": "Configura el botón de disparo/confirmar.",
    "th07 Key Bomb": "Configura el botón de bomba/cancelar.",
    "th07 Key Slow": "Configura el botón de movimiento lento.",
    "th07 Key Skip": "Configura el botón de saltar diálogos.",
    "th07 Key Pause": "Configura el botón de pausa.",
    "th07 Key Up": "Configura el botón de movimiento hacia arriba.",
    "th07 Key Down": "Configura el botón de movimiento hacia abajo.",
    "th07 Key Left": "Configura el botón de movimiento a la izquierda.",
    "th07 Key Right": "Configura el botón de movimiento a la derecha.",
    "th07 Key ShotSlow": "Te mueves más lento al mantener pulsado el botón de disparo.",
    "th07 Key Reset": "Restaurar configuración por defecto.",
    "th07 Key Quit": "Volver al menú anterior.",
    "th08 Menu Spell Practice": "Practicar las Spell Cards de los jefes.",
    "th08 Option BGM Volume": "Ajusta el volumen de la música.",
    "th08 Option SE Volume": "Ajusta el volumen de los efectos de sonido.",
    "th08 Bomb Reimu": "Signo Lunar <Fases de la Luna>",
    "th08 Bomb Reimu Last": "Signo Lunar <Luna Llena de Fantasía en el Zodiaco>",
    "th08 Bomb Yukari": "Calamidad <Arco de Profanación>",
    "th08 Bomb Yukari Last": "Antigua Resurreción <Invocación de la Última Desilusión>",
    "th08 Bomb Marisa": "Prisma de Newton Dividiendo Luz en Elementos",
    "th08 Bomb Marisa Last": "Signo Solar <Sol Brillante Alineado con el Zodiaco>",
    "th08 Bomb Alice": "Signo Floral -Amapola de un Sacrificio",
    "th08 Bomb Alice Last": "Signo Floral -Pesadilla de Flores Multicolor",
    "th08 Spell Dissolve": "\"Conjuro disperso\"",
    "th08 Spell Resurrection": "\"Resurrección\"",
    "th08 Music Room spoiler 1": "*** Nota ***",
    "th08 Music Room spoiler 2": "　Este tema todavía no se ha reproducido en el juego.",
    "th08 Music Room spoiler 3": "　Si todavía no quieres escuchar el tema o ver el comentario,",
    "th08 Music Room spoiler 4": "　será mejor que te alejes lo antes posible.",
    "th08 Music Room spoiler 5": "　",
    "th08 Music Room spoiler 6": "　　(Atención, si pulsas otra vez el botón aceptar, al igual que en los otros temas,",
    "th08 Music Room spoiler 7": "　　se mostrará el comentario y se reproducirá el tema, así que cuidado)",
    "th08 config": "Configuración de Touhou Eiyashou",
    "th06 up": "Arriba ",
    "th06 down": "Abajo ",
    "th06 left": "Izquierda ",
    "th06 right": "Derecha ",
    "th06 vertex": "Deshabilitar Vertex Buffer",
    "th06 fog": "Deshabilitar niebla",
    "th06 16bit textures": "Forzar texturas de 16 bits",
    "th06 Gouraud shading": "Limitar uso del sombreado Gouraud",
    "th06 color composition": "No usar composición de colores en texturas",
    "th06 rasterizer mode": "Utilizar modo de rasterización por referencia",
    "th06 clear buffer": "Limpiar backbuffer durante refresco de pantalla",
    "th06 minimum graphics": "Mostrar gráficos mínimos necesarios",
    "th06 depth test": "Desactivar prueba de profundidad",
    "th06 force frame": "Forzar tasa de imágenes a 60FPS",
    "th06 fullscreen": "Pantalla completa",
    "th06 windowed": "Ventana",
    "th06 full rate": "1/1 (predeter.)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32 bits",
    "th06 16bits mode": "16 bits",
    "th06 accept": "Aceptar",
    "th06 cancel": "Cancelar",
    "th06 screen mode": "Estilo de pantalla",
    "th06 refresh rate": "Frecuencia de actualización",
    "th06 colors": "Modo de color",
    "th06 pad X axis": "Eje X del mando (1~1000)",
    "th06 pad Y axis": "Eje Y del mando (1~1000)",
    "th06 check pad": "Comprobar mando",
    "th06 config saved caption": "Confirmación",
    "th06 config saved text": "Configuración guardada",
    "th07 16bits textures": "Forzar uso de texturas de 16 bits",
    "th07 BGM memory": "Precargar BGM en la memoria",
    "th07 draw screen": "Dibujar fondo de pantalla en cada momento",
    "th07 VSync": "Desactivar sincronización vertical",
    "th07 fullscreen": "Pantalla completa (rec.)",
    "th07 low effects": "Feo",
    "th07 medium effects": "Modesto",
    "th07 high effects": "Bello (rec.)",
    "th07 32bits mode": "32 bits (recomen.)",
    "th07 effect quality": "Calidad de efectos",
    "th08 fog": "Deshabilitar niebla (no recomendado)",
    "th08 color composition": "No usar composición de colores en texturas (prohibido)",
    "th08 depth test": "Desactivar prueba de profundidad (no recomendado)",
    "th08 rasterizer mode": "Utilizar modo de rasterización por referencia (prohibido)",
    "th08 VSync": "Desactivar sincronización vertical (no recomendado)",
    "th07 Clear Easy Multiplier": "Easy Rank   *0.5",
    "th07 Clear Normal Multiplier": "Normal Rank  *1.0",
    "th07 Clear Hard Multiplier": "Hard Rank    *1.2",
    "th07 Clear Lunatic Multiplier": "Lunatic Rank *1.5",
    "th06_ascii_fullpower": "!Maximo Poder!",
    "th06_ascii_centered_spell_bonus": "!Bonus de Spell Card!"
}