{
    "0": "\"Locura de Adoración\"",
    "2": "\"Locura de Adoración\"",
    "4": "\"Chispa de Amor de Deviantt\"",
    "6": "\"Gran Chispa de Amor de Deviantt\"",
    "8": "\"Hechizo Infernal de la Bruja\"",
    "10": "\"Hechizo Infernal de la Bruja\"",
    "12": "\"La Sombra de Poder Calamitoso\"",
    "14": "\"La Sombra de Poder Calamitoso\"",
    "16": "\"Verdadera Magia de Azufre\"",
    "18": "\"Verdadera Magia de Azufre\"",
    "20": "\"Sagrada Lluvia de Slimes\"",
    "22": "Sello Prismático \"Iluminación Cristalizada\"",
    "24": "Sello Prismático \"Iluminación Cristalizada\"",
    "26": "\"Sagradas Estrellas Etereas\"",
    "29": "\"Sagradas Estrellas Eternas\"",
    "30": "\"Choque del Carmesí y la Bendición\"",
    "121": "\"Radiante Amanecer\"",
    "34": "\"Llama Susurrante\"",
    "36": "\"Gran Llama Susurrante\"",
    "38": "Azufre \"Magia de la Calamidad\"",
    "40": "Azufre \"Magia de la Maliciosa Calamidad\"",
    "42": "\"Danmaku Infernal\"",
    "44": "\"Malicioso Danmaku Infernal\"",
    "46": "Último Prisma \"Haz del Otro Mundo\"",
    "48": "Último Prisma \"Haz del Otro Mundo\"",
    "50": "\"Ruina de la Luz y el Vacío\"",
    "54": "Constante \"Las Estaciones del Caos\"",
    "58": "Excalibur Iridiscente \"Aparición del Guardián\"",
    "62": "\"Celestial Destrucción\"",
    "66": "\"Futuro de la Resistencia Vacía\"",
    "68": "\"Futuro de la Resistencia Vacía\"",
    "120": "\"Vacío y Constante\"",
    "70": "\"Prólogo del Inicio y Final\"",
    "73": "\"Prólogo del Inicio y Final\"",
    "74": "\"Los 3 Ejes del Caos\"",
    "76": "\"Los 3 Ejes del Caos\"",
    "78": "Último Amanecer del Abismo \"Eclipse\"",
    "80": "Último Amanecer del Abismo \"Eclipse\"",
    "82": "Remanentes del Viejo Dios \"Destrucción, Sacrificio y Muerte\"",
    "84": "Remanentes del Viejo Dios \"Destrucción, Sacrificio y Muerte\"",
    "86": "Guardianes \"Dualidad de los Origenes Impuros\"",
    "88": "Grandes Guardianes \"Dualidad de los Origenes Impuros\"",
    "90": "\"Eternidad de las Almas - Sol Celestial\"",
    "94": "\"Eternidad de las Almas - Estrellas Distantes\"",
    "98": "\"Eternidad de las Almas - Vacío Espacial\"",
    "102": "\"Eternidad de las Almas - Magnífica Nebulosa\"",
    "106": "\"Reavivada Esperanza de 100 años\"",
    "108": "\"Retribución a la Profanadora\"",
    "107": "\"Horrores y Pesadillas de la Profundidad\"",
    "109": "\"Ojo Infernal de Maldad Pura\"",
    "110": "\"Piezas del Cielo Reunidas con Pureza\"",
    "111": "Sello Danmaku \"Barrera de Gensokyo y Terraria\"",
    "112": "Scarlet Devil \"Danmaku del Otro Mundo\"",
    "113": "\"Mortal y Bella Sinfonía Radiante\"",
    "114": "Pasado \"Impío Sufrimiento del Altruista\"",
    "115": "Tirana de los Tiranos \"Barrera de Juicio y Karma\"",
    "116": "Profanación \"Blasfemias Divinas en Castigo\"",
    "117": "\"Última Esperanza de una Tierra\"",
    "118": "\"Viaje de Coronación del Impuro\"",
    "119": "PROFANACIÓN ABSOLUTA \"DESOLACIÓN DE DESTRUCCIÓN IMPURA\""
}