{
    "0": "Símbolo de mariposa \"Escamas diminutas\"",
    "2": "Símbolo de mariposa \"Escamas de papilio\"",
    "4": "Símbolo de mariposa \"Revoloteo veraniego\"",
    "6": "Símbolo de mariposa \"Aleteo de mediados de verano\"",
    "8": "Símbolo de lluvia \"Lluvia otoñal de cautiverio\"",
    "10": "Símbolo de lluvia \"Aguacero maldito\"",
    "12": "Símbolo de filo \"Yamauba afilando su cuchillo\"",
    "14": "Símbolo de filo \"Yamauba afilando su cuchillo oni\"",
    "16": "Símbolo del último día \"Asesinato en la montaña\"",
    "18": "Símbolo del último día \"Sangriento asesinato en la montaña\"",
    "20": "Símbolo de primavera \"Primavera sorpresiva\"",
    "22": "Símbolo de perro \"Paseo del perro callejero\"",
    "24": "Símbolo canino \"Paseo del perro de montaña\"",
    "26": "Peonza \"Taparrabos Komainu\"",
    "29": "Peonza \"Acurrúcate y muere\"",
    "30": "Símbolo de guardián \"Solo y en armonía\"",
    "121": "\"Radiante Amanecer\"",
    "34": "Símbolo mágico \"Bodhi instantáneo\"",
    "36": "Símbolo mágico \"Bodhi inpromptu\"",
    "38": "Símbolo magico \"Gólem Bala\"",
    "40": "Símbolo mágico \"Mascota bala viviente gigante\"",
    "42": "Jizo \"Salvación criminal\"",
    "44": "Jizo \"Salvación infernal\"",
    "46": "Último Prisma \"Haz del Otro Mundo\"",
    "48": "Último Prisma \"Haz del Otro Mundo\"",
    "50": "Recuento de la Historia \"Piedra Eterna\"",
    "54": "Constante \"Las Estaciones del Caos\"",
    "58": "Excalibur Iridiscente \"Aparición del Guardián\"",
    "62": "\"Celestial Destrucción\"",
    "66": "Danza alocada \"Tengu-odoshi\"",
    "68": "Danza alocada \"Locura asusta-tengu\"",
    "120": "\"Vacío y Constante\"",
    "70": "\"Prólogo del Inicio y Final\"",
    "73": "\"Prólogo del Inicio y Final\"",
    "74": "\"Los 3 Ejes del Caos\"",
    "76": "\"Los 3 Ejes del Caos\"",
    "78": "Otoño oculto \"Muere de malnutrición\"",
    "80": "Otoño oculto \"Muerte por plaga negra de inanición\"",
    "82": "Invierno oculto \"Muñeco de nieve negra\"",
    "84": "Invierno oculto \"Muñeco de nieve de nevada abnormal\"",
    "86": "Primavera oculta \"Hechicero de abril\"",
    "88": "Primavera oculta \"Encantador de flores cayentes abnormales\"",
    "90": "Eternidad de las Almas (Melee)",
    "94": "Eternidad de las Almas (Invocador)",
    "98": "Eternidad de las Almas (Ranger)",
    "102": "Eternidad de las Almas (Mago)",
    "106": "Danza del tambor \"Aplausos poderosos\"",
    "108": "\"Retribución a la Profanadora\"",
    "107": "\"Vacío y Pesadillas de la Profundidad\"",
    "109": "\"La Torre de Mordor\"",
    "110": "\"Siete Partes de la Tenebrosa Alma\"",
    "111": "Sello Danmaku \"Barrera de Gensokyo y Terraria\"",
    "112": "Scarlet Devil \"Danmaku del Otro Mundo\"",
    "113": "\"Sinfonía Radiante\"",
    "114": "\"Infernal Profanación de la Maldad\"",
    "115": "\"Barrera de Juicio y Karma\"",
    "116": "\"Blasfemias Divinas en Castigo\"",
    "117": "\"Última Esperanza de Terraria\"",
    "118": "Profanación \"Tiranía Arrazada por el Impuro\"",
    "119": "PROFANACIÓN ABSOLUTA \"DESOLACIÓN DE DESTRUCCIÓN IMPURA\""
}