{
    "0": "Símbolo de Flora \"Raíz Punzante\"",
    "2": "Símbolo de Flora \"Raíz Punzante Florecida\"",
    "4": "\"Maldición del Génesis de la Vida\"",
    "6": "\"Catástrofe del Génesis de la Vida\"",
    "8": "\"Témpano Recayente\"",
    "10": "\"Témpano en Descongelación\"",
    "12": "Símbolo de Nieve \"Mariposa Criógena\"",
    "16": "Símbolo de Hielo \"Montaña Cristalizada\"",
    "18": "Símbolo de Hielo \"Tierra Cristalizada\"",
    "20": "Sello de Fuego \"Ceniza Infernal\"",
    "22": "Sello de Fuego \"Ceniza Infernal\"",
    "23": "Sello de Fuego \"Ceniza del Infierno\"",
    "24": "Sello Volcano \"Resurgiente Magma\"",
    "26": "Sello Volcano \"Resurgiente Lava\"",
    "27": "Sello Volcano \"Resurgiente Tambora\"",
    "28": "\"Mano del Espíritu de Fuego\"",
    "30": "\"Mano del Espíritu de Fuego\"",
    "31": "\"Mano del Dios de Fuego\"",
    "32": "Sello Astral \"Baile del Cosmos\"",
    "36": "\"Anillo de Polvo Estelar\"",
    "38": "\"Anillo de Meteoros\"",
    "39": "\"Antiguo Anillo de Meteoros\"",
    "40": "Sello Cósmico \"Lado Oscuro de Dos Planetas\"",
    "101": "\"Nuevos Pilares de la Creación\"",
    "44": "Clima \"Reaparición del Sol Escondido\"",
    "46": "Clima \"Reaparición del Sol Entre Tempestad\"",
    "48": "Clima \"Violenta Unión de Vientos\"",
    "50": "Clima \"Calamidad de Vientos en Nubarrones\"",
    "52": "\"Paisaje Templado Cambiante\"",
    "54": "\"Paisaje Templado en Calentamiento Global\"",
    "56": "\"Altura Divisoria del Clima\"",
    "58": "\"Cordillera Divisoria del Clima\"",
    "102": "Dios del Clima \"Tormenta Divína Interminable\"",
    "60": "Elemento Arcano \"Brillo Puro\"",
    "62": "Elemento Arcano \"Destello Puro\"",
    "64": "\"Resplandor de un Portador de Luz\"",
    "66": "\"Resplandor de Lucifer\"",
    "68": "\"Flor Luminiscente\"",
    "70": "\"Flor de Luminiscencia Divina\"",
    "72": "Poder Antiguo \"Creación del Color\"",
    "74": "Poder Ancestral \"Creación del Color\"",
    "76": "Sello de Luz \"Prisma de Rayos Inalcanzables\"",
    "80": "Lighderiu \"Espada que Elimina Sombras\"",
    "84": "\"Luz Ancestral contra la Guerra Sombría\"",
    "88": "Batalla de Defensa \"Escudo de Estrellas\"",
    "89": "Símbolo Protector \"Gran Barrera de Doble Carbino\"",
    "90": "Diosa Protectora \"Alma Impenetrable\"",
    "91": "\"Princesa de las Tinieblas Ahuyenta Luces\"",
    "92": "Símbolo de la Muerte \"Vacío para el Psicópata\"",
    "93": "Símbolo de la Muerte \"Destructor de Almas Viles\"",
    "94": "Trascendencia \"Juicio Final para Paz\"",
    "95": "Justicia del Dios de la Muerte \"Purga de Asesinos\"",
    "96": "Borde de la Vida \"Portal del Pentagrama\"",
    "97": "\"Resentimiento del Mundo Oscuro\"",
    "98": "\"Locura por una Guerra sin Sentido\"",
    "99": "\"Masacre Imperdonable\"",
    "100": "Derrame Sin Fin \"Holocausto de los Divinos\"",
    "103": "Civilización de Rojo Sangre \"Guerra Milenaria\""
}