{
    "0": "Flora Sign \"Pungent Root\"",
    "2": "Flora Sign \"Flowering Pungent Root\"",
    "4": "\"Curse of Life Genesis\"",
    "6": "\"Catastrophe of Life Genesis\"",
    "8": "\"Relapsing Iceberg\"",
    "10": "\"Iceberg in Defrosting\"",
    "12": "Snow Sign \"Cryogenic Butterfly\"",
    "16": "Ice Sign \"Cristalized Mountain\"",
    "18": "Ice Sign \"Cristalized Earth\"",
    "20": "Fire Sign \"Infernal Ash\"",
    "22": "Fire Sign \"Infernal Ash\"",
    "23": "Fire Sign \"Ashes of Hell\"",
    "24": "Volcano Seal \"Resurgent Magma\"",
    "26": "Volcano Seal \"Resurgent Lava\"",
    "27": "Volcano Seal \"Resurgent Tambora\"",
    "28": "\"Hand of the Fire Spirit\"",
    "30": "\"Hand of the Fire Lord\"",
    "31": "\"Hand of the Fire God\"",
    "32": "Astral Seal \"Dance of Cosmos\"",
    "36": "\"Ring of Stardust\"",
    "38": "\"Ring of Meteors\"",
    "39": "\"Ancient Ring of Meteors\"",
    "40": "Cosmic Seal \"Dark Side of Two Planets\"",
    "101": "\"New Pillars of Creation\"",
    "44": "Weather \"Reappearance of the Hidden Sun\"",
    "46": "Weather \"Reappearance of the Sun Amidst the Storm\"",
    "48": "Weather \"Violent Winds Union\"",
    "50": "Weather \"Wind Calamity in Clouds\"",
    "52": "\"Changing Temperate Landscape\"",
    "54": "\"Temperate Landscape in Global Warming\"",
    "56": "\"Climate Dividing Height\"",
    "58": "\"Climate Dividing Mountain Range\"",
    "102": "Weather God \"Neverending Divine Storm\"",
    "60": "Arcane Element \"Pure Bright\"",
    "62": "Arcane Element \"Pure Gleam\"",
    "64": "\"Brilliance of a Light Bearer\"",
    "66": "\"Lucifer's Brilliance\"",
    "68": "\"Luminiscent Flower\"",
    "70": "\"Flower of Divine Luminiscence\"",
    "72": "Old Power \"Creation of Color\"",
    "74": "Ancient Power \"Creation of Color\"",
    "76": "Light Sign \"Unattainable Rays' Prism\"",
    "80": "Lighderiu \"Sword that Deletes Shadows\"",
    "84": "\"Ancient Light against Shadow War\"",
    "88": "Defense Battle \"Stars' Shield\"",
    "89": "Protector Sign \"Great Barrier of Double Carbyne\"",
    "90": "Protector Goddess \"Impenetrable Soul\"",
    "91": "\"Princess of Darkness Drives Away Lights\"",
    "92": "Death Sign \"Void for the Psycho\"",
    "93": "Death Sign \"Destroyer of Vile Souls\"",
    "94": "Trascendence \"Final Destination for Peace\"",
    "95": "Justice of the Death God \"Purge of Assasins\"",
    "96": "Border of Life \"Pentagram Portal\"",
    "97": "\"Resentment of the Dark World\"",
    "98": "\"Madness by a Senseless War\"",
    "99": "\"Unforgivable Massacre\"",
    "100": "Endless Bloodsheed \"Holocaust of the Divines\"",
    "103": "Civilization in Red-Blood \"Millenary War\""
}