{
    "0": "Magic Sign \"Strange Starry Beam\"",
    "2": "Magic Sign \"Unknown Starry Ray\"",
    "4": "Star Sign \"Shooting the Word\"",
    "6": "Star Sign \"Shooting to a Rumor\"",
    "8": "\"Star Magic Assault\"",
    "12": "\"Silent, Forgotten Violence\"",
    "14": "\"Silent, Forgotten Hell\"",
    "16": "\"Empty Memory of a Profane Land\"",
    "18": "\"Darkened Memory of a Profane Land\"",
    "20": "\"Soul of an Unstoppable Power\"",
    "22": "\"Soul of an Unstoppable Force\"",
    "24": "\"Buddha's Treasure\"",
    "26": "\"Buddha's Holy Treasure\"",
    "28": "Vajra \"Path to Divity\"",
    "30": "Vajra \"Path to Illumination\"",
    "32": "Light Sign \"Pure Halo\"",
    "36": "Clairvoyance \"Embracing Buddhism Faith\"",
    "40": "Reverse Hierarchy \"Counterattacker Move\"",
    "42": "Reverse Hierarchy \"The Attacker and Counterattacker\"",
    "44": "Turnabout \"Inverted Yin Yang Sides\"",
    "46": "Turnabout \"Inverted Heaven\"",
    "48": "Turnabout \"Time Running In\"",
    "52": "Reverse Bow \"Mirrored Bullet-Self\"",
    "113": "Reverse Sign \"Cursed Front Shot\"",
    "117": "Reverse Sign \"Cursed Back Shot\""
}