{
    "0": "Sello de Luciérnaga «Meteoros Terrestres»",
    "1": "Sello de Luciérnaga «Cometas Terrestres»",
    "2": "Sello de Lámpara «Fenómeno de la Luciérnaga»",
    "3": "Sello de Lámpara «Fenómeno de la Luciérnaga»",
    "4": "Sello de Lámpara «Fenómeno de la Luciérnaga»",
    "5": "Sello de Lámpara «Fenómeno de la Luciérnaga»",
    "6": "Sello de Retorcimiento «Pequeños Insectos»",
    "7": "Sello de Retorcimiento «Tormenta de Pequeños Insectos»",
    "8": "Sello de Retorcimiento «Tormenta de Insectos Nocturnos»",
    "9": "Sello de Retorcimiento «Tornado de Insectos Nocturnos»",
    "10": "Insecto Oculto «Seclusión de la Noche Eterna»",
    "11": "Insecto Oculto «Seclusión de la Noche Eterna»",
    "12": "Insecto Oculto «Seclusión de la Noche Eterna»",
    "13": "Sello Vocal «Ululando en la Noche»",
    "14": "Sello Vocal «Ululando en la Noche»",
    "15": "Sello Vocal «Alarido del Búho Real»",
    "16": "Sello Vocal «Alarido del Búho Real»",
    "17": "Sello de Polilla «Maleficio del Insecto de la Esfinge Colibrí»",
    "18": "Sello de Polilla «Maleficio del Insecto de la Esfinge Colibrí»",
    "19": "Sello Tóxico «Escamas de la Polilla Venenosa»",
    "20": "Toxina Mortífera «Danza Oscura de la Polilla Venenosa»",
    "21": "Sello de Halcón «Vuelo Fatídico»",
    "22": "Sello de Halcón «Vuelo Fatídico»",
    "23": "Sello de Halcón «Vuelo Fatídico»",
    "24": "Sello de Halcón «Vuelo Fatídico»",
    "25": "Ceguera Nocturna «Canto del Gorrión Nocturno»",
    "26": "Ceguera Nocturna «Canto del Gorrión Nocturno»",
    "27": "Ceguera Nocturna «Canto del Gorrión Nocturno»",
    "28": "Ceguera Nocturna «Canto del Gorrión Nocturno»",
    "29": "Gorrión Nocturno «Directora de Coro de Medianoche»",
    "30": "Gorrión Nocturno «Directora de Coro de Medianoche»",
    "31": "Gorrión Nocturno «Directora de Coro de Medianoche»",
    "32": "Nacimiento Espiritual «Pirámide Primigenia»",
    "33": "Nacimiento Espiritual «Pirámide Primigenia»",
    "34": "Nacimiento Espiritual «Pirámide Primigenia»",
    "35": "Nacimiento Espiritual «Pirámide Primigenia»",
    "36": "Sello de los Orígenes «Efimeridad 137»",
    "37": "Sello de los Orígenes «Efimeridad 137»",
    "38": "Sello de los Orígenes «Efimeridad 137»",
    "39": "Sello de la Ambición «Crisis de Buretsu»",
    "40": "Sello de la Ambición «Crisis de Masakado»",
    "41": "Sello de la Ambición «Crisis de Yoshimitsu»",
    "42": "Sello de la Ambición «Crisis de los Cuarteles Generales»",
    "43": "Sello Soberano «Tres Tesoros Sagrados- Espada»",
    "44": "Sello Soberano  «Tres Tesoros Sagrados - Orbe»",
    "45": "Sello Soberano  «Tres Tesoros Sagrados - Espejo»",
    "46": "Soberanía «Nación de los Tres Tesoros Sagrados»",
    "47": "Sello Final «Emperador Fantasmal»",
    "48": "Sello Final «Emperador Fantasmal»",
    "49": "Seudohistoria «La Leyenda de Gensokyo»",
    "50": "Seudohistoria «La Leyenda de Gensokyo»",
    "51": "Futuro «Reino de los Dioses»",
    "52": "Futuro «Reino de los Dioses»",
    "53": "Futuro «Reino de los Dioses»",
    "54": "Signo lunar -Cuchillos en la barrera divina",
    "55": "Signo lunar -Cuchillos en la barrera divina",
    "56": "Signo lunar -Cuchillos en la barrera divina",
    "57": "Signo lunar -Cuchillos en la barrera divina",
    "58": "Sello elemental -Implosión de opuestos",
    "59": "Sello elemental -Implosión de opuestos",
    "60": "Sello elemental -Implosión de opuestos",
    "61": "Sello elemental -Implosión de opuestos",
    "62": "Sello de barrera elemental -Complementación del Wu xing",
    "63": "Sello de barrera elemental -Complementación del Wu xing",
    "64": "Sello de barrera elemental -Complementación del Wu xing",
    "65": "Sello de barrera elemental -Complementación del Wu xing",
    "66": "Sello lunar -Fases de la luna",
    "67": "Sello lunar -Fases de la luna",
    "68": "Sello lunar -Fases de la luna",
    "69": "Sello lunar -Fases de la luna",
    "70": "Sello de barrera lunar -Cara oculta de la luna",
    "71": "Sello de barrera lunar -Cara oculta de la luna",
    "72": "Sello de barrera lunar -Cara oculta de la luna",
    "73": "Sello de barrera lunar -Cara oculta de la luna",
    "74": "Sello elemental ilimitado -Límites de las fuerzas naturales",
    "75": "Sello elemental ilimitado -Límites de las fuerzas naturales",
    "76": "Sello elemental ilimitado -Límites de las fuerzas naturales",
    "77": "Signo del Eclipse Solar -parcial- <Ver directamente al sol>",
    "78": "Signo del Eclipse Solar -parcial- <Ver directamente al sol>",
    "79": "Signo del Eclipse Solar -parcial- <Ver directamente al sol>",
    "80": "Signo del Eclipse Solar -parcial- <Ver directamente al sol>",
    "81": "Signo Refractario <Luz blanca dividida>",
    "82": "Signo Refractario <Luz blanca dividida>",
    "83": "Signo Refractario <Luz blanca dividida>",
    "84": "Signo Refractario <Luz blanca dividida>",
    "85": "Signo Solar <Rayo de Energía>",
    "86": "Signo Solar <Rayo de Energía>",
    "87": "Signo Solar <Rayo de Energía>",
    "88": "Signo Solar <Rayo de Energía>",
    "89": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "90": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "91": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "92": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "93": "Signo Solar <Energía Solar en destellos a todo color>",
    "94": "Signo Solar <Energía Solar en destellos a todo color>",
    "95": "Signo Solar <Energía Solar en destellos a todo color>",
    "96": "Signo Solar <Energía Solar en destellos a todo color>",
    "97": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "98": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "99": "Signo de Luz y color <Prisma de Newton dividiendo luz en elementos>",
    "100": "Sello Ondulante «Hipnosis  de Ojos Rojos (Perturbación Mental)»",
    "101": "Sello Ondulante «Hipnosis de Ojos Rojos (Perturbación Mental)»",
    "102": "Onda Ilusoria «Hipnosis de Ojos Rojos (Estallido Mental)»",
    "103": "Onda Ilusoria «Hipnosis de Ojos Rojos (Estallido Mental)»",
    "104": "Sello Lunático «Sintonización Alucinógena (Sintonización Premonitora)»",
    "105": "Sello Lunático «Sintonización Alucinógena (Sintonización Premonitora)»",
    "106": "Mirada Lunática «Sintonización de Mirada Lunática (Rastreador de Ilusiones)»",
    "107": "Mirada Lunática «Sintonización de Mirada Lunática (Rastreador de Ilusiones)»",
    "108": "Sello de la Pereza «Cese de la Vida y el Espíritu (Onda Estacionaria)»",
    "109": "Sello de la Pereza «Cese de la Vida y el Espíritu (Onda Estacionaria)»",
    "110": "Indolencia «Cese de Vida y Espíritu (Cese Mental)»",
    "111": "Indolencia «Cese de Vida y Espíritu (Cese Mental)»",
    "112": "Sello Disperso «Luna de la Verdad (Luna Llena Invisible)»",
    "113": "Sello Disperso «Luna de la Verdad (Luna Llena Invisible)»",
    "114": "Sello Disperso «Luna de la Verdad (Luna Llena Invisible)»",
    "115": "Sello Disperso «Luna de la Verdad (Luna Llena Invisible)»",
    "116": "Ojos Lunares «Mesmerismo Remoto de la Coneja Lunar (Telemesmerismo)»",
    "117": "Ojos Lunares «Mesmerismo Remoto de la Coneja Lunar (Telemesmerismo)»",
    "118": "Ojos Lunares «Mesmerismo Remoto de la Coneja Lunar (Telemesmerismo)»",
    "119": "Esfera Espacial «El Cosmos en un Frasco»",
    "120": "Esfera Espacial «El Cosmos en un Frasco»",
    "121": "Esfera Espacial «El Cosmos en un Frasco»",
    "122": "Esfera Espacial «El Cosmos en un Frasco»",
    "123": "Despertar del Dios «Memorias de la Era Divina»",
    "124": "Despertar del Dios «Memorias de la Era Divina»",
    "125": "Sello Divino «Genealogía de los Celestiales»",
    "126": "Sello Divino «Genealogía de los Celestiales»",
    "127": "Renacer «El juego de la Vida»",
    "128": "Renacer «El juego de la Vida»",
    "129": "Resurrección «Juego del Resurgimiento»",
    "130": "Resurrección «Juego del Resurgimiento»",
    "131": "Dios Guía «Dispositivo de Omoikane»",
    "132": "Dios Guía «Dispositivo de Omoikane»",
    "133": "Mente Divina «Cerebro de Omoikane»",
    "134": "Mente Divina «Cerebro de Omoikane»",
    "135": "Maldición Celestial «Apolo 13»",
    "136": "Maldición Celestial «Apolo 13»",
    "137": "Maldición Celestial «Apolo 13»",
    "138": "Maldición Celestial «Apolo 13»",
    "139": "Esoterismo «Entierro Astronómico»",
    "140": "Esoterismo «Entierro Astronómico»",
    "141": "Esoterismo «Entierro Astronómico»",
    "142": "Esoterismo «Entierro Astronómico»",
    "143": "Medicina Prohibida «Elixir de Hourai»",
    "144": "Medicina Prohibida «Elixir de Hourai»",
    "145": "Medicina Prohibida «Elixir de Hourai»",
    "146": "Medicina Prohibida «Elixir de Hourai»",
    "147": "Sello Medicinal «Gran Galaxia en un Frasco»",
    "148": "Sello Medicinal «Gran Galaxia en un Frasco»",
    "149": "Sello Medicinal «Gran Galaxia en un Frasco»",
    "150": "Sello Medicinal «Gran Galaxia en un Frasco»",
    "151": "Guerra Prismática -Flor Arcoíris",
    "152": "Guerra Prismática -Flor Arcoíris",
    "153": "Guerra Prismática -Flor Arcoíris",
    "154": "Guerra Prismática -Flor Arcoíris",
    "155": "Danza Brillante -Pray To The Sun",
    "156": "Danza Brillante -Pray To The Sun",
    "157": "Danza Brillante -Pray To The Sun",
    "158": "Danza Brillante -Pray To The Sun",
    "159": "Convocación Radiante -Arcoíris Catastrófico",
    "160": "Convocación Radiante -Arcoíris Catastrófico",
    "161": "Convocación Radiante -Arcoíris Catastrófico",
    "162": "Convocación Radiante -Arcoíris Catastrófico",
    "163": "Sello de la Diosa Hada -Pernos Luminiscentes",
    "164": "Sello de la Diosa Hada -Pernos Luminiscentes",
    "165": "Sello de la Diosa Hada -Pernos Luminiscentes",
    "166": "Sello de la Diosa Hada -Pernos Luminiscentes",
    "167": "Arco Multicolor -Sueño Arcoíris",
    "168": "Arco Multicolor -Sueño Arcoíris",
    "169": "Arco Multicolor -Sueño Arcoíris",
    "170": "Arco Multicolor -Sueño Arcoíris",
    "171": "Deseo de Pureza -Imperio Bendíto",
    "172": "Deseo de Pureza -Imperio Bendíto",
    "173": "Deseo de Pureza -Imperio Bendíto",
    "174": "Deseo de Pureza -Imperio Bendíto",
    "175": "Diosa de la Bendición -Concentra la luz",
    "176": "Diosa de la Bendición -Concentra la luz",
    "177": "Diosa de la Bendición -Concentra la luz",
    "178": "Diosa de la Bendición -Concentra la luz",
    "179": "Sello del Sol -Eternidad para el Día-",
    "180": "Sello del Sol -Eternidad para el Día-",
    "181": "Sello del Sol -Eternidad para el Día-",
    "182": "Sello del Sol -Eternidad para el Día-",
    "183": "Danmaku Infernal -Fuego Prismático",
    "184": "Danmaku Infernal -Fuego Prismático",
    "185": "Danmaku Infernal -Fuego Prismático",
    "186": "Danmaku Infernal -Fuego Prismático",
    "187": "AMANECER - Brillo Etéreo",
    "188": "AMANECER - Brillo Etéreo",
    "189": "AMANECER - Brillo Etéreo",
    "190": "AMANECER - Brillo Etéreo",
    "191": "Apocalipsis <Siete iglesias de Sardis>",
    "192": "Signo Hermético <El Cábala>",
    "193": "Arte Esoterico <Kuji-in>",
    "194": "Dark souls de los Metroidvania",
    "195": "Teorias Fumadas",
    "196": "Espera interminable",
    "197": "Se un gordito",
    "198": "Teorias Fumadas 2",
    "199": "Guardián de los gorditos",
    "200": "1% ddel poder de Zote",
    "201": "Teorias Fumadas 3",
    "202": "\"Hollow Manía\"",
    "203": "\"SILKSONG SALE MAÑANA\"",
    "204": "\"SILKSONG SALE MAÑANA\"",
    "205": "Tormenta de Mariposas Fuera de Temporada",
    "206": "Ave Ciega Nocturna",
    "207": "Emperador del País del Sol Naciente",
    "208": "Mirada de la Difusa Luna Fantasmal (Ojos Rojos Lunáticos)",
    "209": "Red Capturadora de Mariposas de la Araña Celestial",
    "210": "Absoluto Destello de la Diosa Bendita",
    "211": "SILKSONG NO SALE MAÑANA",
    "212": "Embustera Ancestral",
    "213": "Mateo 2:9-10 <Estrella de Belén>",
    "214": "Signo lunar -Luna llena de fantasía en el zodíaco",
    "215": "Signo Solar -Sol Brillante Alineado con El Zodíaco",
    "216": "Mundo Deflacionario",
    "217": "Corte Reflector del Festival Lunar",
    "218": "Signo del Crepúsculo -Penumbras de Almas Florales", 
    "219": "Destino Escarlata",
    "220": "Paranirvana Saigyouji",
    "221": "Sello de un Viaje -Tierra de la Calamitad Profanada e Iluminada"
}