{
    "th11 Dialog Game Start": "Start!",
    "th14 Dialog Prompt": "Select the resolution:",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720 (If you have issues)",
    "th14 Dialog 1280": "1280×960 (Recomended)",
    "th14 Dialog Fullscreen": "Game In Full Screen",
    "th14 Dialog Always ask": "Always ask",
    "th18 Trophy Get": "You Have an Achievement!:",
    "th18 Dialog Window 1280": "Ventana (1280×960)",
    "th18 Dialog Window 1920": "Ventana (1920×1440)",
    "th18 Dialog Window 2560": "Ventana (2560×1920)",
    "th18 Dialog Fullscreen 1280": "Pantalla Full (1280×960)",
    "th18 Dialog Window 960": "Ventana (960×720)",
    "th18 Dialog Window 640": "Ventana (640×480)",
    "th18 Dialog Fullscreen 640": "Pantalla Full (640×480)",
    "th18 Dialog Fullscreen 960": "Pantalla Full (960×720)",
    "th20": "Touhou Pure Reform ~ Peace to Gensokyo's Order",
    "th20 charname Reimu Hakurei full": "Reimu Hakurei",
    "th20 charname Marisa Kirisame full": "Okina Matara",
    "th20 option fullscreen 640": "Full screen (640×480)",
    "th20 option screen": "Adjust display settings",
    "th20 option bgm volume": "Adjust the volume of music.",
    "th20 option se volume": "Adjust the volume of sound effects.",
    "th20 option key config": "Change controller settings.",
    "th20 option default": "Restore settings to default.",
    "th20 option quit": "Go back from the Option menu.",
    "th20 option key quit": "Return from the KeyConfig menu.",
    "th20 option key shot": "SHOT button, CONFIRM button.",
    "th20 option key spellcard": "SPELLCARD button, CANCEL button.",
    "th20 option key slow": "Focused movement button.",
    "th20 option key pause": "PAUSE button.",
    "th20 option key up": "UP button.",
    "th20 option key down": "DOWN button.",
    "th20 option key left": "LEFT button.",
    "th20 option key right": "RIGHT button.",
    "th20 option key button quit": "Return from the KeyConfig menu.",
    "th20 clear red level": "Void Sword Level　　　%d",
    "th20 clear blue level": "Eternal Summon Level　　　%d",
    "th20 clear yellow level": "Profanation Bow Level　　　%d",
    "th20 clear green level": "Destruction Magic Level　　　%d",
    "th20 clear bonus": "Clear Bonus　　　%s",
    "th20 notice new gem": "Additional \"%s\" stone obtained.",
    "th20 notice equip": "Shot A, Shot B, and Buff Stone slots unlocked.",
    "th20 weapon amount": "No. owned",
    "th20 clear status": "Clear Status",
    "th20 config": "Touhou Makakushin - Environment Custom Program",
    "th20 JP": "Peace to Gensokyo's Order",
    "th20 option key device": "Press LEFT and RIGHT to configure keys for different input devices.",
    "th20 option key reset": "Restore key configurations to default.",
    "th20 option key prompt": "Press in sequence to assign new keys.",
    "th20 option fullscreen 960": "Full screen (960×720)",
    "th20 option fullscreen 1280": "Full screen (1280×960)",
    "th20 option window 640": "Windowed (640×480)",
    "th20 option window 960": "Windowed (960×720) (If you have issues)",
    "th20 option window 1280": "Windowed (1280×960)",
    "th20 option window 1920": "Windowed (1920×1440)",
    "th20 option window 2560": "Windowed (2560×1920)",
    "th20 option borderless dot": "Borderless Windowed (DOT by DOT) *Recommended",
    "th20 option borderless": "Borderless Windowed",
    "th20 notice Reimu extra unlock": "Reimu's \"%s\"",
    "th20 notice Marisa extra unlock": "Okina's \"%s\"",
    "th20 notice extra unlock": "has been unlocked for Extra Mode.",
    "th20 gameover hint": "Additional Guardian Stone available by withdrawing now or at completion.",
    "th20 spellpractice unavailable": "Play it on Main Story First."
}