{
    "th11 Dialog Game Start": "Start!",
    "th14 Dialog Prompt": "Select the resolution:",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720 (If you have issues)",
    "th14 Dialog 1280": "1280×960 (Recomended)",
    "th14 Dialog Fullscreen": "Game In Full Screen",
    "th14 Dialog Always ask": "Always ask",
    "th18 Trophy Get": "You Have an Achievement!:",
    "th18 Dialog Window 1280": "Ventana (1280×960)",
    "th18 Dialog Window 1920": "Ventana (1920×1440)",
    "th18 Dialog Window 2560": "Ventana (2560×1920)",
    "th18 Dialog Fullscreen 1280": "Pantalla Full (1280×960)",
    "th18 Dialog Window 960": "Ventana (960×720)",
    "th18 Dialog Window 640": "Ventana (640×480)",
    "th18 Dialog Fullscreen 640": "Pantalla Full (640×480)",
    "th18 Dialog Fullscreen 960": "Pantalla Full (960×720)",
    "th19 no card": "There's nothing",
    "th19 ability random": "Ability Card: Random",
    "th19 rules barrier manual": "Manual Only",
    "th19 rules barrier short": "Short Time",
    "th19 rules barrier long": "Long Time",
    "th19 rules cards all": "Select All",
    "th19 rules cards random": "Random",
    "th19 rules cards none": "Nothing",
    "th19 rules cards choose": "Character's Only",
    "th19 rules matches 1": "1 Math",
    "th19 rules matches 2": "2 Matches",
    "th19 rules matches 3": "3 Matches",
    "th19 0 min": "Nope",
    "th19 rules title": "Server Settings",
    "th19 rules time": "Time Limit",
    "th19 rules rounds": "Number of Rounds",
    "th19 rules cards": "Ability Card",
    "th19 rules life 1p": "Life (J1)",
    "th19 rules life 2p": "Life (J2)",
    "th19 rules barrier 1p": "Shield(J1)",
    "th19 rules barrier 2p": "Shield (J2)",
    "th19 rules default": "Default",
    "th19 rules quit": "Close Settings",
    "th19 net connected": "¡Conectao!",
    "th19 net playername 1": "Player Name",
    "th19 net alphanumeric": "Only Alphanumers and Some Symbols.",
    "th19 net roomrename 1": "Server Name",
    "th19 net roomrename 2": "Porfavor inserta el nombre del server del jugador al que quieres unirte.",
    "th19 net room joining": "Entrando...",
    "th19 net room joined": "You Entered!",
    "th19 net waiting for opponent": "Esperando por oponentes.",
    "th19 net connection failed": "No hay conexión.",
    "th19 net failed": "Ooofff",
    "th19 net try again": "Intenta otra vez.",
    "th19 net joined p1": "Se encontró un oponente. Eres el jugador 1 (Izquierda).",
    "th19 net joined p2": "Se encontró un oponente. Eres el jugador 2 (Derecha).",
    "th19 net wait for p1": "Esperando a que el Jugador 1 haga algo.",
    "th19 net start": "Presiona el botón de acción para comenzar.",
    "th19 net change delay": "Puedes cambiar los ajustes de retraso para ambos lados.",
    "th19 net latency low": "Baja latencia.",
    "th19 net latency low notice": "Bajo: mejor para conexiones de alta velocidad.",
    "th19 net latency mid": "Media latencia.",
    "th19 net latency mid notice": "Algo operable: bueno para conexiones que están por ahí.",
    "th19 net latency high": "Alta latencia",
    "th19 net latency high notice": "Ma o meno: Para pcs callampas.",
    "th19 net latency none": "Sin latencia",
    "th19 rules barrier none": "No Shield",
    "th19": "Touhou An Universe ~ Journey Of Multiple Apocaliptic Dimentions",
    "th19 JP": "Jorney Of Multiple Apocaliptic Dimensions"
}