{
    "th11 Dialog Game Start": "Start!",
    "th14 Dialog Prompt": "Select the resolution:",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720 (If you have issues)",
    "th14 Dialog 1280": "1280×960 (Recomended)",
    "th14 Dialog Fullscreen": "Game In Full Screen",
    "th14 Dialog Always ask": "Always ask",
    "th18 Trophy Get": "You Have an Achievement!:",
    "th18 Dialog Window 1280": "Ventana (1280×960)",
    "th18 Dialog Window 1920": "Ventana (1920×1440)",
    "th18 Dialog Window 2560": "Ventana (2560×1920)",
    "th18 Dialog Fullscreen 1280": "Pantalla Full (1280×960)",
    "th18 Dialog Window 960": "Ventana (960×720)",
    "th18 Dialog Window 640": "Ventana (640×480)",
    "th18 Dialog Fullscreen 640": "Pantalla Full (640×480)",
    "th18 Dialog Fullscreen 960": "Pantalla Full (960×720)",
    "th19 rules barrier manual": "Manual",
    "th19 rules barrier short": "Poco tiempo",
    "th19 rules barrier long": "Largo tiempo",
    "th19 rules cards all": "Seleccionar todo",
    "th19 rules cards random": "Random",
    "th19 rules cards none": "Nada",
    "th19 rules cards choose": "Propias solamente",
    "th19 rules matches 1": "1 Ronda",
    "th19 rules matches 2": "2 Rondas",
    "th19 rules matches 3": "3 Rondas",
    "th19 0 min": "Nope",
    "th19 rules title": "Ajustes Servidor",
    "th19 rules time": "Tiempo límite",
    "th19 rules rounds": "Numero de rondas",
    "th19 rules cards": "Carta de Habilidad",
    "th19 rules life 1p": "Vida (J1)",
    "th19 rules life 2p": "Vida (J2)",
    "th19 rules barrier 1p": "Escudo (J1)",
    "th19 rules barrier 2p": "Escudo (J2)",
    "th19 rules default": "Default",
    "th19 rules quit": "Cerrar Ajustes",
    "th19 net connected": "¡Conectao!",
    "th19 net playername 1": "Nombre del Jugador",
    "th19 net alphanumeric": "Solo alfanuméricos y algunos símbolos",
    "th19 net roomrename 1": "Nombre del Server",
    "th19 net roomrename 2": "Porfavor inserta el nombre del server del jugador al que quieres unirte.",
    "th19 net room joining": "Entrando...",
    "th19 net room joined": "¡Entraste!",
    "th19 net waiting for opponent": "Esperando por oponentes.",
    "th19 net connection failed": "No hay conexión.",
    "th19 net failed": "Ooofff",
    "th19 net try again": "Dale otra vez.",
    "th19 net joined p1": "Se encontró un oponente. Eres el jugador 1 (Izquierda).",
    "th19 net joined p2": "Se encontró un oponente. Eres el jugador 2 (Derecha).",
    "th19 net wait for p1": "Esperando a que el Jugador 1 haga algo.",
    "th19 net start": "Presiona el botón de acción para comenzar.",
    "th19 net change delay": "Puedes cambiar los ajustes de retraso para ambos lados.",
    "th19 net latency low": "Baja latencia.",
    "th19 net latency low notice": "Bajo: mejor para conexiones de alta velocidad.",
    "th19 net latency mid": "Media latencia.",
    "th19 net latency mid notice": "Algo operable: bueno para conexiones que están por ahí.",
    "th19 net latency high": "Alta latencia",
    "th19 net latency high notice": "Ma o meno: Para pcs callampas.",
    "th19 net latency none": "Sin latencia",
    "th19 rules barrier none": "No Shield",
    "th19": "Touhou A Universe ~ Journey Of Multiple Apocaliptic Dimentions",
    "th19 config": "Touhou A Universe - Environment Custom Program",
    "th19 JP": "Journey of Multiple Apocaliptic Dimensions",
    "th19 VS Mode": "Modo Versus",
    "th19 Online VS Mode": "Modo Online",
    "th09 Story Mode": "Iniciar Historia",
    "th19 Achievement": "Logros",
    "th19 Music Room": "Sala de Música",
    "th19 Option": "Ajustes",
    "th19 Manual": "Tutorial",
    "th19 Quit": "Salir",
    "th19_warning": "Alerta!",
    "th19_extra_attack_level": "Ataque Extra lvl %d",
    "th19_extra_attack": "Ataque Extra!",
    "th19_boss_attack_level": "Ataque de Jefe lvl %d",
    "th19_boss_attack": "Ataque de Jefe!",
    "th19_menu_charge": "Cargar",
    "th19_menu_up": "Arriba",
    "th19_menu_down": "Abajo",
    "th19_menu_left": "Izquierda",
    "th19_menu_right": "Derecha",
    "th185 unequip": "Quitar",
    "th19 no card": "¡Sin cartas!",
    "th19 ability random": "Carta de Habilidad aleatoria"
}