{
    "th08_09": "Maiden's Capricho ~ Dream Battle (RichaadEB)",
    "th08_10": "Love Colored Master Spark (FalKKonE)",
    "th08_15": "Empress Of Light (RichaadEB)",
    "th08_16": "Gensokyo Millenium ~ History Of The Moon (FalKKonE)",
    "th08_18": "Reach For The Moon ~ Immortal Smoke (FalKKonE)",
    "th08_21": "Necrofantasia (FalKKonE)",
    "th11_01": "The Tale of a Cruel World",
    "th11_02": "Unholy Ambush",
    "th11_03": "Unholy Insurgency",
    "th11_04": "The Heaven-Sent Abomination",
    "th11_05": "Feral Amalgamation",
    "th11_06": "Murderswarm",
    "th11_07": "Roar of The Jungle Dragon (Instrumental)",
    "th11_08": "Scourge of The Universe",
    "th11_09": "Universal Collapse",
    "th11_10": "Signal Received",
    "th11_11": "Catastrophyc Fabrications",
    "th11_12": "Stained, Brutal Calamity (Grief-Lament)",
    "th11_13": "Stained, Brutal Calamity (Epiphany)",
    "th11_14": "Trial of The Insane",
    "th11_15": "Twisted Garden",
    "th11_16": "Stained, Brutal Calamity (Acceptance)",
    "th11_17": "Storms Before Catastrophe",
    "th15_02": "Forgotten Crossroads",
    "th15_03": "False Knight",
    "th15_04": "Resting Grounds",
    "th15_05": "Dream Battle",
    "th15_06": "Birthplace",
    "th15_07": "Broken Vessel",
    "th15_08": "Kingdom's Edge",
    "th15_09": "Daughter Of Hallownest",
    "th15_10": "Grimm",
    "th15_11": "Nightmare King (Metal)",
    "th15_12": "Dreamers",
    "th15_13": "Radiance (Metal)",
    "th15_14": "Haunted Foes",
    "th15_15": "Pure Vessel (Metal)",
    "th15_16": "Enter Hallownest",
    "th15_17": "Hollow Knight (E. Metal)",
    "th16_01": "Mystic Dream ~ Snow or Cherry Petal (ssbbmaster)",
    "th16_02": "Every Adventure Has a Beginning",
    "th16_03": "Sparkly Strawberry Sunrise (Yuri 0)",
    "th16_04": "Sinkholes of Darkness",
    "th16_05": "Raw, Unflitered Calamity",
    "th16_06": "Shining Kaleidoscope ~ Prismatic Radiance",
    "th16_07": "Empress of Light (RichaadEB)",
    "th16_08": "Step Below Hell",
    "th16_09": "Stained, Brutal Calamity (Lament)",
    "th16_10": "A Maiden's Illusionary Funeral ~ Necrofantasy (FalKKonE)",
    "th16_11": "Collective Consciousness (MGR:R)",
    "th16_12": "Jump Into Battle (Phyrnna)",
    "th16_13": "As The Shadow (Phyrnna)",
    "th16_14": "The Hot Wind Blowing (MGR)",
    "th16_15": "Rum, Woman, Victory (Ensiferum)",
    "th16_16": "Below The Surface",
    "th16_17": "Hartmman Youkai Girl ~ Last Remote (ssbbmaster)",
    "th19_01": "A Phantom's Boisterous Dance (SN)",
    "th19_02": "Lunar Clock ~ Luna Dial (F)",
    "th19_03": "Lace (F)",
    "th19_04": "NECROMANCIA (H)",
    "th19_05": "Strawberry Crisis!! (F)",
    "th19_06": "Hartmann Youkai Girl (F)",
    "th19_07": "Reincarnation (F)",
    "th19_08": "Sleeping Terror (F)",
    "th19_09": "The Venerable Ancient Battlefield (S)",
    "th19_10": "Pandemonic Planet (F)",
    "th19_11": "Pure Furies ~ Wereabouts of the Heart (F)",
    "th19_12": "Reach for the Moon ~ Immortal Smoke (F)",
    "th19_13": "Legendary Illusion ~ Infinite Being (SN)",
    "th19_14": "The Stains of Time (M)",
    "th19_15": "Lullaby of Deserted Hell (R)",
    "th19_16": "Collective Consciousness (M)",
    "th19_17": "Raw, Unfiltered Calamity (D)",
    "th19_18": "Entrust this World to Idols ~ Idolatrize World (F)",
    "th19_19": "Now, Until the Moment You Die (S)",
    "th19_20": "Flight of the Bamboo Cutter ~ Lunatic Princess (F)",
    "th19_21": "End of Daylight (SN)",
    "th19_22": "Bad Apple!! (S)"
}