{
    "th19_01": "A Phantom's Boisterous Dance (SN)",
    "th19_02": "Lunar Clock ~ Luna Dial (F)",
    "th19_03": "Lace (F)",
    "th19_04": "The Devil Made Us Do It (D)",
    "th19_05": "Strawberry Crisis!! (F)",
    "th19_06": "Hartman Youkai Girl (F)",
    "th19_07": "Reincarnation (F)",
    "th19_08": "Sleeping Terror (F)",
    "th19_09": "The Venerable Ancient Battlefield (S)",
    "th19_10": "Pandemonic Planet (F)",
    "th19_11": "Pure Furies ~ Wereabouts of the Heart (F)",
    "th19_12": "Reach for the Moon ~ Immortal Smoke (F)",
    "th19_13": "Legendary Illusion ~ Infinite Being (SN)",
    "th19_14": "The Stains of Time (M)",
    "th19_15": "This City Bleeds for You (D)",
    "th19_16": "Collective Consciousness (M)",
    "th19_17": "Raw Unfiltered Calamity (D)",
    "th19_18": "Entrust this World to Idols ~ Idolatrize World (F)",
    "th19_19": "Now, Until the Moment You Die (S)",
    "th19_20": "Flight of the Bamboo Cutter ~ Lunatic Princess (F)",
    "th19_21": "End of Daylight (SN)",
    "th19_22": "Bad Apple!! (S)"
}