{
    "0": "Guardián \"Lanza del Sol\"",
    "2": "Llama \"Danmaku Elíseo\"",
    "4": "Llama de Absolución \"Danmaku Elíseo\"",
    "6": "Diosa Profanada \"Furia Pristina\"",
    "8": "Destello Profano \"Gran Furia Pristina\"",
    "10": "Disparo Fantasma \"Minas fantasmales\"",
    "12": "Disparo Explosivo Fantasmal \"Minas fantasmales\"",
    "14": "Necroplasma \"Alma en pena\"",
    "16": "Necroplasma \"Alma ruinosa\"",
    "18": "Polterghast \"Revelador del Destino\"",
    "20": "Polterghast \"Revelador del Destino\"",
    "22": "Fantoplasma \"Veganza de los espíritus\"",
    "24": "Fantoplasma \"Veganza de las almas aflijidas\"",
    "26": "Ira del Dragón \"Danmaku de Llamas\"",
    "30": "\"Tornado Llameante\"",
    "32": "\"Tornado Llameante\"",
    "34": "\"Cielo Ardiente\"",
    "36": "Último Dragón \"Paraíso Ardiente\"",
    "38": "\"Rugido del Dragón de la Jungla\"",
    "40": "Amanecer Final \"Rugido del Dragón de la Jungla\"",
    "42": "\"Pared Láser\"",
    "44": "\"Barrera Láser Cósmica\"",
    "46": "Azote del Universo \"Núcleo de la Nebulosa\"",
    "50": "Collapso Universal \"Busqueda de Dioses\"",
    "54": "Devorador del Universo \"Danmaku del Asesino de Dioses\"",
    "58": "Azote del Universo \"Centinelas del Devorador\"",
    "62": "Collapso Universal \"Infierno del Asesino de Dioses\"",
    "66": "Devorador del Universo \"Descarga Cósmica\"",
    "70": "Azote del Universo \"Viento de la Muerte\"",
    "74": "Collapso Universal \"Guardianes Cósmicos\"",
    "78": "Devorador del Universo \"Excelsus\"",
    "82": "Vacío Incesante \"Primaverales muñecas de Kyoto\"",
    "86": "Tejedor de Tormentas \"Muñeca de paja kamikaze\"",
    "90": "Signus \"Retorno a la inanimacidad\"",
    "94": "Vacío Incesante \"Veneno de mercurio\"",
    "98": "Tejedor de Tormentas \"Princesa ondina\"",
    "102": "Signus \"Piedra filosofal\"",
    "106": "Vacíó Incesante \"Brazo extensible\"",
    "110": "Tejedor de Tormentas \"Pororoca de kappa\"",
    "114": "Signus \"Trauma en las vislumbres profundidades\"",
    "118": "\"Plaga Milagrosa\"",
    "120": "Materia Milagrosa \"Terror Mecánico\"",
    "122": "Artemis y Apollo \"Mega División de Átomos\"",
    "124": "Artemis y Apollo \"Omega División de Átomos\"",
    "126": "Thanatos \"Destructor de Materia\"",
    "128": "Thanatos \"Destructor Nuclear de Materia\"",
    "130": "Ares \"Arsenal de Guerra\"",
    "132": "Ares \"Arsenal de Guerra Cuádruple\"",
    "134": "Hekate \"Nanomáquina Infernal\"",
    "136": "Hekate \"Nanomáquina de Guerra Infernal\"",
    "138": "\"Explosión Nuclear Tesla\"",
    "142": "Perdición \"Busca Almas\"",
    "144": "Perdición \"Busca Almas\"",
    "145": "Perdición \"Busca Almas Supremos\"",
    "146": "Vehemencia \"Hex de Vulnerabilidad\"",
    "147": "Vehemencia \"Hex de Vulnerabilidad\"",
    "148": "Vehemencia \"Hex de Vulnerabilidad\"",
    "149": "Vehemencia \"Hechizo de Vulnerabilidad\"",
    "150": "Condena \"Dardos de Azufre\"",
    "152": "Condena \"Dardos de Azufre\"",
    "153": "Condena \"Dardos de Azufre\"",
    "154": "\"Danmaku Susurrante\"",
    "156": "\"Danmaku Catastrófico Susurrante\"",
    "158": "\"Cenizas de la Calamidad\"",
    "160": "Calamidad \"Cenizas de la Aniquilación\"",
    "162": "Almas de la Eternidad \"Campeón Maestro\"",
    "163": "\"Calamitoso Fin del Viaje\"",
    "164": "Guardián de Terraria \"El Pilar de la Invocación\"",
    "165": "\"Corte del Juicio\"",
    "166": "\"Estrella Collapsante\"",
    "167": "\"Chispas Solares\"",
    "168": "\"Estallido Estelar\"",
    "169": "La Mano de Chronos \"Reloj Divino\"",
    "170": "Supernova \"Explosión Galáctica\"",
    "171": "Deidad de la Luz \"Cuchilladas Brillantes\"",
    "172": "\"Disparo de Libertad\"",
    "173": "Poder de Deidad \"Creación\"",
    "174": "\"Gran Genesis de Terraria\""
}